watch:
  - buffer: 127.0.0.1:8000
    queue:
      action: stop
      length: 200
      restart_cooldown: 6s
      container:
        - labels: [queue-sdk-client-label1, queue-sdk-client-label2]
    egress:
      action: restart
      restart_cooldown: 6s
      idle: 100s
      container:
        - labels: egress-sdk-client-label
        - labels: some-label
    ingress:
      action: restart
      restart_cooldown: 6s
      idle: 50s
      container:
        - label: ingress-sdk-client-label
