watch:
  - buffer: 127.0.0.1:8000
    queue:
      action: stop
      length: 1990
      restart_cooldown: 60s
      container:
        - labels: [queue-client-label1, queue-client-label2=2]
    egress:
      action: restart
      restart_cooldown: 60s
      idle: 60s
      container:
        - labels: egress-client-label=egress-client-value
        - labels: some-label
    ingress:
      action: restart
      restart_cooldown: 30s
      idle: 30s
      container:
        - labels: ingress-client-label=3
